### ISSUE TITLE
Limit

### ISSUE THREAD

**Issue by hahohihia** [gregl83/mknft#1]
hello,
is it possible when add more different layers, but to limit the combinations that the script will provide.
I mean when we have traits for 100k different combinations, can I limit the script to make only 10k?

**Comment by gregl83** [comment]
Hi @curlcrest!

The package needs more work and documentation but does include a `size` parameter when packaging your NFTs.

You can put a value smaller than the total number of combinations possible with your layers (e.g. 10000).

For a reference in code: https://github.com/gregl83/mknft/blob/main/src/main.rs#L55

Does this solve your problem?

**Comment by hahohihia** [comment]
Sorry, where I can put the value, because I am not that familiar with code. :(

**Comment by gregl83** [comment]
You can run `mknft` with the `--help` option, including sub-commands, to see examples of execution statements. For example:  `mknft package --help`.

If you wanted to limit your NFT size to 10,000 the `prepare` command would be called like so:

`mknft package ./path/to/prepared ./path/to/packaged 10000`

**Comment by gregl83** [comment]
I believe this question has been answered and is resolved. Closing unless indicated otherwise.
